# Generated by Django 2.2.2 on 2019-06-18 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stylist_beta', '0001_initial'),
        ('customer_beta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist_beta.StylistProfile'),
        ),
        migrations.AddField(
            model_name='reserveandhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_beta.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='reserveandhistory',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist_beta.Menu'),
        ),
    ]
