# Generated by Django 2.2.2 on 2019-06-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_beta', '0002_auto_20190618_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='img',
            field=models.ImageField(upload_to='customer_img'),
        ),
    ]
